### LOGIN
POST https://formcamapi-production.up.railway.app/api/v1/login
Content-Type: application/json

{
  "sap": "11043122",
  "password": "Mka957351*"
}

### CRIAR USUÁRIO
POST https://formcamapi-production.up.railway.app/api/v1/users/create_user
Content-Type: application/json

{
  "name": "clisamax",
  "sap": "11043122",
  "password": "Mka957351*"
}

### DELETAR USUÁRIO
DELETE https://formcamapi-production.up.railway.app/api/v1/users/delete_user/6c25de2d-b66b-45a1-8b81-a6fe7f9e4e0a
Content-Type: application/json
Authorization: Bearer <TOKEN_AQUI>

### ATUALIZAR USUÁRIO
PUT https://formcamapi-production.up.railway.app/api/v1/users/update_user/d02bd326-e291-44b8-b089-151f90d970cc
Content-Type: application/json
Authorization: Bearer <TOKEN_AQUI>

{
  "name": "Max",
  "sap": "11043119",
  "password": "Mka957351*"
}

### CRIAR PRODUTO
POST https://formcamapi-production.up.railway.app/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhN2ZhMDhlLWJlNDctNGYwNS04MWYzLWE5ZWQ5MGU4ZmUxNCIsInNhcCI6IjExMDQzMTIyIiwibmFtZSI6ImNsaXNhbWF4IiwiaWF0IjoxNzU3OTcwODU2LCJleHAiOjE3NTgwNTcyNTZ9.W9w_pXCyQIbAJw-5XJB5LuipGHPFqfyhLmvgCe4Vd0A


{
  "name": "Produto Teste",
  "product": "Tipo",
  "quantity": 10,
  "unit": "unidade",
  "nameOfResponsible": "Responsável",
  "occurrenceDate": "2024-06-01T00:00:00.000Z"
}

### CRIAR OCORRÊNCIA
POST https://formcamapi-production.up.railway.app/api/v1/occurrences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhN2ZhMDhlLWJlNDctNGYwNS04MWYzLWE5ZWQ5MGU4ZmUxNCIsInNhcCI6IjExMDQzMTIyIiwibmFtZSI6ImNsaXNhbWF4IiwiaWF0IjoxNzU3OTcwODU2LCJleHAiOjE3NTgwNTcyNTZ9.W9w_pXCyQIbAJw-5XJB5LuipGHPFqfyhLmvgCe4Vd0A

{
  "origin": "Origem Teste",
  "process": "Processo Teste",
  "procedure": "Procedimento Teste",
  "responsible": "Responsável Teste",
  "description": "Descrição Teste",
  "note": "Nota Teste"
}